apiVersion: v1
kind: Pod
metadata:
  name: phpinfo-po
  label: 
    app: phpinfo
    branch: santander
spec:
  containers: 
    -
      args:
        - -f
        - src/index.php
        - -S 
        - 0.0.0.0:8080
      command:
        - /usr/bin/php
      env:
        - 
          name: author
          value: IsmaelPulido
        -
          name: JAVA_HOME
          value: /var/lib/java
      image: ipulido/phpinfo:santander
      name: phpinfo-container
      ports:
        -
          containerPort: 8080
          protocol: TCP
      volumeMounts:
        -
          mountPath: /src/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: /src/index.php
  volumes:
    - 
      configMap:
        defaultMode: 0400
        items:
          - 
            key: index.php
            mode: 0400
            path: index.php
        name: phpinfo-cm
        #kubectl create cm --from-file ./src/index.php phpinfo-cm
      name: phpinfo-volume
