name: CI
on:
  push:
    branches:
      - santander
env:
  uuid: 77720140
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps: 
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: build
        run: docker build --file Dockerfile --tag phpinfo:${uuid} .
      -
        name: run
        run: docker run -d --entrypoint /usr/bin/php --name phpinfo -p 80:8000 -v ${PWD}/srv/index.php:/srv/index.php:ro phpinfo:${uuid} -f src/index.php -S 0.0.0.0:8080
      -
        name: test
        run: while true; do sleep 10; curl localhost/srv/index.php | grep phpinfo &&break; done
  swarm:
    runs-on: ubuntu-18.04
    steps: 
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: build
        run: docker build --file Dockerfile --tag phpinfo:${uuid} .
      -
        name: swarm
        run: docker swarm init
      -
        name: compose
        run: sed -i /node.role/s/worker/manager/docker-compose.yaml
      -
        name: nodeport
        run: sed -i /8080:8080/s/8080/80/ docker-compose.yaml
      -
        name: deploy
        run: docker stack deploy -c docker-compose.yaml phpinfo
      -
        name: temp
        run: ifconfig
      -
        name: test
        run: while true; do sleep 10; curl localhost/srv/index.php | grep phpinfo &&break; done
  #kubernetes:
  #openshift:
